### ISSUE TITLE
Feedback 16 - Static Client Registration

### ISSUE THREAD

**Issue by fahadbinrahat** [cdr-register/register#16] opened 2019-08-02 05:32 UTC
Clarifications sought for the followings:

As clarified in the [comment ](https://github.com/ConsumerDataStandardsAustralia/standards/issues/79#issuecomment-517116289), that dynamic client registration is not adopted, how static registration will address following concerns:

- If client registrations are done at ACCC, how client Ids are expected to be created at DH end, required for authentication and authorisation flows?

Besides this [component diagram](https://cdr-register.github.io/register/#ecosystem-component-diagram) , a sequence diagram will really help exhibiting flows in aforementioned concern.

**Comment by JamesMBligh** [comment] 2019-08-04 02:56
This looks like a duplicate of #3 from my read

**Comment by CDR-Register-Stream** [comment] 2019-09-24 22:12
Dynamic Client Registration was chosen as the registration method for the CDR Ecosystem. Design discussion  is located at https://github.com/cdr-register/register/issues/25

**Closed by CDR-Register-Stream** 2019-09-24 22:12 UTC
