### ISSUE TITLE
Typo in ClientRegistration

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#64] opened 2020-02-25 13:02 UTC
Looks like a typo from copy and paste of UK specification, TPP should be Data Recipient:
![image](https://user-images.githubusercontent.com/4291448/75249896-43a5d180-582b-11ea-8572-221414bc0cf0.png)

**Comment by perlboy** [comment] 2020-02-25 13:12
Also, could clarity be provided on the description of the `iss` field here?
![image](https://user-images.githubusercontent.com/4291448/75250508-9cc23500-582c-11ea-99d7-3ffd9a3ebf70.png)

Is the "unique identifier issued by the Register" a reference to the `dataHolderBrandId` ?

**Comment by CDR-Register-Stream** [comment] 2020-04-20 01:18
@perlboy Thanks for raising this issue. I have updated the swagger, correcting the defintions.
They are now as follows:


iss | string | true | none | Contains the identifier for the ADR Software Product (SoftwareProductId) as defined in the CDR Register
-- | -- | -- | -- | --
iat | integer(int32) | true | none | The time at which the request was issued by the Data Recipient expressed as seconds since 1970-01-01T00:00:00Z as measured in UTC



This issue has now been resolved and documented in release 1.1.1.

Closing as complete

**Closed by CDR-Register-Stream** 2020-04-20 01:18 UTC
Labels: api, query
