### ISSUE TITLE
Dynamic client registration-Delete End Point HTTP status code 405

### ISSUE THREAD

**Issue by sowmya-NY** [cdr-register/register#60] opened 2020-02-24 09:33 UTC
We are not clear about difference between 403 and 405 HTTP status codes for the dynamic client registration delete end point.

Description for both status codes is same:
The client does not have permission to read, update or delete the Client.

URL for reference:
https://cdr-register.github.io/register/#delete-a-client-registration-for-a-given-client-id

**Comment by perlboy** [comment] 2020-02-24 11:09
RFC 7231 specifies 405 as:
```The 405 (Method Not Allowed) status code indicates that the method received in the request-line is known by the origin server but not supported by the target resource.```

While 403 is specified as:
```The 403 (Forbidden) status code indicates that the server understood the request but refuses to authorize it.  A server that wishes to make public why the request has been forbidden can describe that reason in the response payload (if any).```

I'm sure ACCC will clarify but I would hazard a guess that a 403 would be thrown for an unauthorised request to this endpoint (for DELETE, PUT, GET) and a 405 would occur for an invalid method (ie. POST) to `/register/{ClientId}`.

**Comment by CDR-Register-Stream** [comment] 2020-03-25 22:11
This is a duplicate of #35 The confusion probably stems from the description in the swagger for 405 being the same as 403. 

Given that the Delete endpoint is currently an optional endpoint, I would expect this error code to be returned if it is unsupported.

**Closed by CDR-Register-Stream** 2020-03-25 22:11 UTC
Labels: duplicate, query
