### ISSUE TITLE
Inconsistency between register specifications and standards on authentication of the register

### ISSUE THREAD

**Issue by WestpacOpenBanking** [cdr-register/register#45] opened 2020-01-07 03:02 UTC
The register standard for [CDR Register Calling Participant Admin API using Client Authentication](https://cdr-register.github.io/register/#cdr-register-calling-participant-admin-api-using-client-authentication) specifies that the CDR register will authenticate to participants using a client assertion presented to the resource server, i.e. by using the client_id, client_assertion_type, client_assertion and potentially grant_type request parameters.
 
The data standard for [CDR Register calling Data Holders and Data Recipients specifies](https://consumerdatastandardsaustralia.github.io/standards/#cdr-register-calling-data-holders-and-data-recipients) that the CDR register will authenticate to participants using a client assertion presented in the authorization request header.
                                                                                                                    
Which approach is intended? We have [also posted an issue](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/89) on the standards-maintenance GitHub repository.

**Comment by CDR-Register-Stream** [comment] 2020-01-30 22:31
The standards reflect the intended behaviour. The CDR Register documentation will be updated to reference the CDS rather than duplicate this content

**Comment by CDR-Register-Stream** [comment] 2020-03-25 21:41
Updates to the documentation were made in [release 1.1.0](https://cdr-register.github.io/register/includes/releasenotes/releasenotes.1.1.0.html#security-profile)

Closing as complete

**Closed by CDR-Register-Stream** 2020-03-25 21:41 UTC
